"""Add AI fields

Revision ID: a64a87703542
Revises: fca2aefe7671
Create Date: 2026-08-21 09:09:22.623554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64a87703542'
down_revision: Union[str, Sequence[str], None] = 'fca2aefe7671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('ai_involved', sa.Boolean(), nullable=True))
    op.add_column('audit_events', sa.Column('ai_model_used', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('ai_model_version', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('ai_recommendation', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('prompt_injection_detected', sa.Boolean(), nullable=True))
    op.add_column('risk_decisions', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_decisions', 'ai_analysis')
    op.drop_column('audit_events', 'prompt_injection_detected')
    op.drop_column('audit_events', 'ai_recommendation')
    op.drop_column('audit_events', 'ai_model_version')
    op.drop_column('audit_events', 'ai_model_used')
    op.drop_column('audit_events', 'ai_involved')
    # ### end Alembic commands ###
